# Generated by Django 4.0.5 on 2022-06-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('REVIEWER', 'Reviewer'), ('REVIEW_ASKER', 'Review_asker')], max_length=50, null=True, verbose_name='Role'),
        ),
    ]
