# Generated by Django 4.0.5 on 2022-07-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("SUBSCRIPTION", "SUBSCRIPTION")],
                max_length=50,
                null=True,
                verbose_name="Role",
            ),
        ),
    ]
